services:
  php:
    image: rising-patterns-php:dev
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/app/
    networks:
      - app_network

#  nginx:
#    image: rising-patterns-nginx:dev
#    build:
#      context: ./docker/nginx
#    volumes:
#      - ./:/var/www/symfony/
#    ports:
#      - "9001:80"
#    networks:
#      - app_network
#
#  db:
#    image: mysql:8
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: noPassword
#      MYSQL_DATABASE: rising-patterns
#    volumes:
#      - db-data:/var/lib/mysql
#    ports:
#      - "3306:3306"
#    networks:
#      - app_network

#volumes:
#  db-data:

networks:
  app_network: